apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
{{ include "pgadmin.labels" . | indent 4 }}
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pgadmin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
