persistance:
  accessModes:
    - ReadWriteOnce
  size: 7Gi

postgresqlUsername: postgres

postgresqlPassword: bad455

postgresqlDatabase: hasura

resources:
  limits:
    memory: 128Mi
    cpu: 150m
