image:
  tag: 5
wordpressEmail: change-me@okteto.com
wordpressUsername: admin
wordpressPassword: admin
allowEmptyPassword: false

wordpressFirstName: FirstName
wordpressLastName: LastName
wordpressBlogName: User's Blog!

wordpressScheme: https

mariadb:
  db:
    name: admin
    user: admin

  rootUser:
    password: admin

  master:
    persistence:
      size: 5Gi

persistence:
  size: 5Gi


updateStrategy:
  type: Recreate

service:
  type: ClusterIP
  annotations:
    dev.okteto.com/auto-ingress: "true"
