service:
  type: ClusterIP
  annotations:
    dev.okteto.com/auto-ingress: "true"

persistance:
  size: 5Gi

env:
  email: chart@example.local
  password: SuperSecret

resources:
  limits:
    memory: 256Mi
    cpu: 500m
