service:
  type: ClusterIP
  annotations:
    dev.okteto.com/auto-ingress: "true"

persistance:
  size: 3Gi

env:
  email: postgres@pgdb-postgresql.izzatzr.svc.cluster.local
  password: bad455

resources:
  limits:
    memory: 320Mi
    cpu: 300m

