db:
  host: database-mariadb.jay-del.svc.cluster.local

service:
  type: ClusterIP

ingress:
  enabled: true
  #certManager: true
  annotations:
    dev.okteto.com/generate-host: "true"
  #  dev.okteto.com/auto-ingress: "true"
