db:
  host: lamp-lamp.infra-futuraworks.svc.cluster.local

service:
  type: ClusterIP

ingress:
  enabled: true
  certManager: true
  annotations:
    dev.okteto.com/auto-ingress: "true"

resources:
  limits:
    memory: 256Mi
    cpu: 200m

