postgresqlImage:
  debug: true

pgpoolImage:
  debug: true

postgresql:
  replicaCount: 2
  resources:
    limits:
      cpu: 300m
      memory: 320Mi
  username: postgres
  password: bad455
  database: hasura
  repmgrUsername: repmgrx
  repmgrPassword: repmgrxxx

pgpool:
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 288Mi
  adminUsername: postgres
  adminPassword: bad455

persistance:
  accessModes:
    - ReadWriteMany
  size: 5Gi
