image:
  repository: bitnami/wordpress
  tag: 5

wordpressEmail: admin@lpec.com
wordpressUsername: admin
wordpressPassword: admin
allowEmptyPassword: false

wordpressFirstName: admin
wordpressLastName: admin
wordpressBlogName: lpecwebpage

wordpressScheme: https
wordpressSkipInstall: true

mariadb:
  db:
    name: admin
    user: admin

  rootUser:
    password: admin

  master:
    accessMode: ReadWriteOnce
    persistence:
      size: 5Gi

persistence:
  size: 5Gi

updateStrategy:
  type: Recreate

service:
  type: ClusterIP
  annotations:
    dev.okteto.com/auto-ingress: "true"
