image:
  debug: true

rootUser:
  password: abcdef123

service:
  type: NodePort
  nodePort: 
    master: 30001
    slave: 30002

master:
  resources:
    limits:
      memory: 512Mi
      cpu: 200m
  replicas: 2

slave:
  resources:
    limits:
      memory: 256Mi
      cpu: 100m
  replicas: 2
