image:
  debug: true

rootUser:
  password: bad455

service:
  type: ClusterIP
  port: 3306

db:
  user: haloservice
  password: halothere

master:
  persistence:
    accessModes: 
      - ReadWriteOnce
    size: 5Gi
  updateStrategy:
    type: RollingUpdate
  resources:
    requests:
      memory: 1Mi
      cpu: 1m

slave:
  replicas: 1
  persistence:
    accessModes:
      - ReadWriteOnce
    size: 3Gi
  updateStrategy:
    type: RollingUpdate
  resources:
    requests:
      memory: 1Mi
      cpu: 1m

tests:
  enabled: false

