image:
  debug: true

rootUser:
  password: abcdef123

service:
  type: ClusterIP
  port: 3306

master:
  resources:
    limits:
      memory: 512Mi
      cpu: 200m
  replicas: 2

slave:
  resources:
    limits:
      memory: 256Mi
      cpu: 100m
  replicas: 2

