ghostProtocol: https
ghostHost: ghost-izzatzr.cloud.okteto.net
# ghostPort:
ghostPath: /

ghostUsername: admin

ghostPassword: 6h0st69111

ghostEmail: admin@halosvc.host

ghostBlogTitle: Halo Service !

mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: ghost
    user: ghost
    password: 6h0st69
  rootUser:
    password: bad455
  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 3Gi
  resources:
    limits:
      memory: 256Mi
      cpu: 250m

service:
  type: ClusterIP
  # HTTP Port
  port: 80
  externalTrafficPolicy: Cluster
  ## Service annotations done as key:value pairs
  annotations:
    dev.okteto.com/auto-ingress: "true"

persistence:
  accessMode: ReadWriteOnce
  size: 5Gi

resources:
  limits:
    memory: 1024Mi
    cpu: 500m

