apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: api
    hasuraService: custom
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: hasura/graphql-engine:v1.0.0
        imagePullPolicy: IfNotPresent
        name: api
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://postgres:bad455@pgdb-postgresql.futuraworks.svc.cluster.local:5432/hasura
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          value: "opikwibu"
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: HASURA_GRAPHQL_JWT_SECRET
          value: '{"type":"HS256", "key": "3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R"}'
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
