apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: api
    hasuraService: custom
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api
    spec:
      containers:
      - image: hasura/graphql-engine:v1.1.0
        imagePullPolicy: IfNotPresent
        name: api
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://postgres:d1c06464c4@pgdb-postgresql.uglpec.svc.cluster.local:5432/uglpec
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          value: "d1c06464c4"
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        - name: HASURA_GRAPHQL_JWT_SECRET
          value: '{"type":"HS256", "key": "062bca0bee7dbce87629c85c841b6a63"}'
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
