apiVersion: v1
kind: Service
metadata:
  labels:
    app: hasura
  name: hasura
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hasura
  type: ClusterIP
